spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}


management:
  endpoints:
    web:
      exposure:
        include: health,info

external:
  newsapi:
    base-url: "https://newsapi.org/v2"
    key: ${NEWSAPI_KEY:}
  newsdata:
    base-url: "https://newsdata.io/api/1"
    key: ${NEWSDATA_KEY:}
  deepsearch:
    base-url: "https://api-v2.deepsearch.com/v1"
    key: ${DEEPSEARCH_KEY:}
  navernewssearch:
    base-url: "https://openapi.naver.com/v1/search"
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}
  gnews:
        base-url: "https://gnews.io/api/v4"
        key: ${GNEWS_KEY:}
  navernewsapi:
    base-url: "https://openapi.naver.com/v1/search"
    client-id: ${NAVERNEWSAPI_CLIENT_ID:}
    client-secret: ${NAVERNEWSAPI_CLIENT_SECRET:}